apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: bs087acdk-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/bs087acdk-dotnet-basic-gitops